ci: Build statically linked bpf-linker in CI
- Download LLVM builds from Rust CI.
- Always link libLLVM statically.
- For now, do it only for x86_64.

diff --git a/.github/workflows/llvm.yml b/.github/workflows/llvm.yml
--- a/.github/workflows/llvm.yml
+++ b/.github/workflows/llvm.yml
@@ -9,6 +9,10 @@ on:
 jobs:
   llvm:
     runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        target:
+          - x86_64-unknown-linux-musl
     name: llvm
     outputs:
       cache-key: ${{ steps.cache-key.outputs.cache-key }}
@@ -20,7 +24,7 @@ jobs:
           echo "sha=$value" >> "$GITHUB_OUTPUT"
 
       - id: cache-key
-        run: echo "cache-key=llvm-${{ steps.ls-remote.outputs.sha }}-1" >> "$GITHUB_OUTPUT"
+        run: echo "cache-key=llvm-${{ matrix.target }}-${{ steps.ls-remote.outputs.sha }}-1" >> "$GITHUB_OUTPUT"
 
       - name: Cache
         id: cache-llvm
@@ -30,8 +34,29 @@ jobs:
           key: ${{ steps.cache-key.outputs.cache-key }}
           lookup-only: true
 
+      - name: Download LLVM from Rust CI
+        id: download-llvm
+        if: steps.cache-llvm.outputs.cache-hit != 'true'
+        run:
+          wget https://ci-artifacts.rust-lang.org/rustc-builds/${{ env.LLVM_SHA }}/rust-dev-nightly-${{ env.LLVM_TARGET }}.tar.xz && \
+            echo "download-llvm=success" << "$GITHUB_OUTPUT" || \
+            echo "download-llvm=failure" << "$GITHUB_OUTPUT"
+
       - name: Install Tools
         if: steps.cache-llvm.outputs.cache-hit != 'true'
+        run:
+          wget https://ci-artifacts.rust-lang.org/rustc-builds/${{ env.LLVM_SHA }}/rust-dev-nightly-${{ env.LLVM_TARGET }}.tar.xz && \
+            echo "success=true" << "$GITHUB_OUTPUT" || \
+            echo "success=false" << "$GITHUB_OUTPUT"
+
+      - name: Save downloaded LLVM in cache
+        if: steps.download-llvm.outputs.success == 'true'
+        run: |
+          set -euxo pipefail
+          tar -xpf rust-dev-nightly-${{ env.LLVM_TARGET }}.tar.xz --strip-components 1 -C llvm-install
+
+      - name: Install Tools
+        if: steps.cache-llvm.outputs.cache-hit != 'true' && steps.download-llvm.outputs.success != 'true'
         run: |
           set -euxo pipefail
           wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
@@ -44,7 +69,7 @@ jobs:
           sudo apt -y install cmake ninja-build clang lld
 
       - name: Checkout LLVM Source
-        if: steps.cache-llvm.outputs.cache-hit != 'true'
+        if: steps.cache-llvm.outputs.cache-hit != 'true' && steps.download-llvm.outputs.success != 'true'
         uses: actions/checkout@v4
         with:
           repository: aya-rs/llvm-project
@@ -52,7 +77,7 @@ jobs:
           path: llvm-project
 
       - name: Configure LLVM
-        if: steps.cache-llvm.outputs.cache-hit != 'true'
+        if: steps.cache-llvm.outputs.cache-hit != 'true' && steps.download-llvm.outputs.success != 'true'
         run: |
           set -euxo pipefail
           cmake \
@@ -73,7 +98,7 @@ jobs:
             -DLLVM_USE_LINKER=lld
 
       - name: Install LLVM
-        if: steps.cache-llvm.outputs.cache-hit != 'true'
+        if: steps.cache-llvm.outputs.cache-hit != 'true' && steps.download-llvm.outputs.success != 'true'
         env:
           # Create symlinks rather than copies to conserve disk space. At the time of this writing,
           # GitHub-hosted runners have 14GB of SSD space
@@ -85,7 +110,7 @@ jobs:
         run: cmake --build llvm-build --target install
 
       - name: Rewrite LLVM Symlinks
-        if: steps.cache-llvm.outputs.cache-hit != 'true'
+        if: steps.cache-llvm.outputs.cache-hit != 'true' && steps.download-llvm.outputs.success != 'true'
         # Move targets over the symlinks that point to them.
         #
         # This whole dance would be simpler if CMake supported CMAKE_INSTALL_MODE=MOVE.
